---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: run script to convert excel to cvs
      ansible.builtin.script: convert-xlsx-to-csv.py
      args:
        executable: python3
    - name: import csv change log
      community.general.read_csv:
        path: 'sheets/Change Log.csv'
      register: change_log
    - name: import interfaces csv
      community.general.read_csv:
        path: 'sheets/Interfaces.csv'
        key: ''
      register: interfaces
    - name: import lookup tables csv
      community.general.read_csv:
        fieldnames:
          - type
          - bartlesville
          - houston
          - alaska
          - canada
          - emea
          - norway
          - norway_tde_cde
          - ap_australia_hub
          - ap_jakarta_hub
          - ap_other
        path: 'sheets/Lookup Table.csv'
        key: type
      register: lookup_table
    - name: import lookup tables csv
      community.general.read_csv:
        path: 'sheets/Router (L3) Config.csv'
        fieldnames:
          - id
          - ignore
          - config
        key: id
      register: router_config
    - name: import lookup tables csv
      community.general.read_csv:
        path: 'sheets/Switch (L2) Config.csv'
      register: switch_config
    - name: print dictionary
      debug:
        msg: "{{ router_config }}"
    - name: print dict
      debug:
        msg: "{{ router_config.dict['57'].config }}"
    - name: generate example config
      ansible.builtin.template:
        src: router_config.j2
        dest: example.conf
    - name: print dictionary
      debug:
        msg: "{{ lookup_table }}"
